name: ğŸŒ» Sunny Braille í´ë¼ì´ì–¸íŠ¸ CI ìë™í™” (Github Actions)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: âœ”ï¸ ë ˆí¬ì§€í† ë¦¬ ê°€ì ¸ì˜¤ê¸°
      uses: actions/checkout@v2
      
    - name: âœ”ï¸ Node.js ì„¤ì¹˜
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: âœ”ï¸ dependencies ì„¤ì¹˜
      run: npm install

    - name: âœ”ï¸ Build í…ŒìŠ¤íŠ¸
      run: npm run build

    - name: âœ”ï¸ Test ì‹¤í–‰
      run: npm test
